
from setuptools import setup, find_packages

setup(
    name="adef",
    version="0.4.0",
    author="Piotr Sobonski",
    author_email="adef@gmail.com",
    description=(""),
    license="TBD",
    keywords="",
    python_requires=">=3.11",
    url="http://adef.github.com",
    packages=find_packages(),
    package_data={"adef": []},
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: TBD License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3.11",
        "Topic :: Scientific/Engineering :: Artificial Intelligence :: Cyber Security",
    ],
    include_package_data=True,
    install_requires=[
        "setuptools",
        "wheel",
        "matplotlib",
        "numpy",
        "pandas",
        "scipy",
        "scikit-learn",
        "psutil",
        "seaborn",
        "fuzzy-c-means",
        "pyyaml",
        "python-pptx",
        "h5py",
        "pyarrow",
        "six",
        "colorama",
        "jinja2",
        "seaborn",
        "joblib",
        "hdbscan",
        "pylint",
        "black",
        "pytz",
        "pygod",
        "pyod",
        "torch",
        "torch_geometric",
        "torch_sparse",
        "torch_scatter",
        "torch_cluster",
        "pykalman",
        "tensorflow",
        "keras",
        "padasip",
        "sphinx",
        "furo",
        "ortools",
        "pulp",
    ],
    tests_require=[
        "none",
    ],
    extras_require={
        "docs": [
            "Sphinx",
            "numpydoc",
        ],
        "tests": [
            "none",
        ],
    },
    options={"bdist_wheel": {"universal": "0"}},
)
